# Generated by Django 2.2.3 on 2019-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('horsepower', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('ptwr', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
