# Generated by Django 2.2.3 on 2019-09-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ptwr',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
